ALTER TABLE public.quiz_questions
ADD COLUMN IF NOT EXISTS question_kn TEXT,
ADD COLUMN IF NOT EXISTS option_a_kn TEXT,
ADD COLUMN IF NOT EXISTS option_b_kn TEXT,
ADD COLUMN IF NOT EXISTS option_c_kn TEXT,
ADD COLUMN IF NOT EXISTS option_d_kn TEXT;
